

#application.properties
#spring.datasource.url=jdbc:mysql://localhost:3306/mil_historia_1?serverTimezone=UTC

#application.yml
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_spring_user?serverTimezone=UTC
    username: root
    password: Kojinanjo1@

server:
  port: 8090
# ===============================
# = JPA / HIBERNATE
# ===============================

  jpa:
    show-sql: true
    ddl-auto: update
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
