

#application.properties
#spring.datasource.url=jdbc:mysql://localhost:3306/mil_historia_1?serverTimezone=UTC

#application.yml
spring:
  datasource:
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
#  datasource:
   url: jdbc:mysql://localhost:3306/mil_historia_1?serverTimezone=UTC
   username: root
   password: Kojinanjo1@
#    password:com.mysql.cj.jdbc.Driver
#hasta luego

server:
  port: 8090
# ===============================
# = JPA / HIBERNATE
# ===============================

  jpa:
    show-sql: true
    ddl-auto: update
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
