

#application.properties
#spring.datasource.url=jdbc:mysql://localhost:3306/mil_historia_1?serverTimezone=UTC

#application.yml
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mil_historia_1?serverTimezone=UTC
#    username:
#    password:

server:
  port: 8090
