

#application.properties
#spring.datasource.url=jdbc:mysql://localhost:3306/mil_historia_1?serverTimezone=UTC

#application.yml
spring:
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/mil_historia_1?serverTimezone=UTC
#    username:
#    password:

server:
  port: 8090
